apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoketest-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smoketest-middleware
  template:
    metadata:
      labels:
        app: smoketest-middleware
    spec:
      containers:
        - name: smoketest-middleware
          image: uhub.service.ucloud.cn/entropypool/smoketest-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/SmoketestMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: smoketest-middleware-config
            items:
              - key: service-conf
                path: SmoketestMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: smoketest-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50770
      targetPort: 50770
    - name: grpc
      port: 50771
      targetPort: 50771
    - name: healthz
      port: 50772
      targetPort: 50772
    - name: prometheus
      port: 50773
      targetPort: 50773
  selector:
    app: smoketest-middleware
