// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/smoketest-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/smoketest-middleware/pkg/db/ent/relatedtestcase"
	"github.com/google/uuid"
)

// RelatedTestCaseQuery is the builder for querying RelatedTestCase entities.
type RelatedTestCaseQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RelatedTestCase
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelatedTestCaseQuery builder.
func (rtcq *RelatedTestCaseQuery) Where(ps ...predicate.RelatedTestCase) *RelatedTestCaseQuery {
	rtcq.predicates = append(rtcq.predicates, ps...)
	return rtcq
}

// Limit adds a limit step to the query.
func (rtcq *RelatedTestCaseQuery) Limit(limit int) *RelatedTestCaseQuery {
	rtcq.limit = &limit
	return rtcq
}

// Offset adds an offset step to the query.
func (rtcq *RelatedTestCaseQuery) Offset(offset int) *RelatedTestCaseQuery {
	rtcq.offset = &offset
	return rtcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rtcq *RelatedTestCaseQuery) Unique(unique bool) *RelatedTestCaseQuery {
	rtcq.unique = &unique
	return rtcq
}

// Order adds an order step to the query.
func (rtcq *RelatedTestCaseQuery) Order(o ...OrderFunc) *RelatedTestCaseQuery {
	rtcq.order = append(rtcq.order, o...)
	return rtcq
}

// First returns the first RelatedTestCase entity from the query.
// Returns a *NotFoundError when no RelatedTestCase was found.
func (rtcq *RelatedTestCaseQuery) First(ctx context.Context) (*RelatedTestCase, error) {
	nodes, err := rtcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{relatedtestcase.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) FirstX(ctx context.Context) *RelatedTestCase {
	node, err := rtcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelatedTestCase ID from the query.
// Returns a *NotFoundError when no RelatedTestCase ID was found.
func (rtcq *RelatedTestCaseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rtcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{relatedtestcase.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rtcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelatedTestCase entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelatedTestCase entity is found.
// Returns a *NotFoundError when no RelatedTestCase entities are found.
func (rtcq *RelatedTestCaseQuery) Only(ctx context.Context) (*RelatedTestCase, error) {
	nodes, err := rtcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{relatedtestcase.Label}
	default:
		return nil, &NotSingularError{relatedtestcase.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) OnlyX(ctx context.Context) *RelatedTestCase {
	node, err := rtcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelatedTestCase ID in the query.
// Returns a *NotSingularError when more than one RelatedTestCase ID is found.
// Returns a *NotFoundError when no entities are found.
func (rtcq *RelatedTestCaseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rtcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{relatedtestcase.Label}
	default:
		err = &NotSingularError{relatedtestcase.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rtcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelatedTestCases.
func (rtcq *RelatedTestCaseQuery) All(ctx context.Context) ([]*RelatedTestCase, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rtcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) AllX(ctx context.Context) []*RelatedTestCase {
	nodes, err := rtcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelatedTestCase IDs.
func (rtcq *RelatedTestCaseQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := rtcq.Select(relatedtestcase.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rtcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rtcq *RelatedTestCaseQuery) Count(ctx context.Context) (int, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rtcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) CountX(ctx context.Context) int {
	count, err := rtcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rtcq *RelatedTestCaseQuery) Exist(ctx context.Context) (bool, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rtcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rtcq *RelatedTestCaseQuery) ExistX(ctx context.Context) bool {
	exist, err := rtcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelatedTestCaseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rtcq *RelatedTestCaseQuery) Clone() *RelatedTestCaseQuery {
	if rtcq == nil {
		return nil
	}
	return &RelatedTestCaseQuery{
		config:     rtcq.config,
		limit:      rtcq.limit,
		offset:     rtcq.offset,
		order:      append([]OrderFunc{}, rtcq.order...),
		predicates: append([]predicate.RelatedTestCase{}, rtcq.predicates...),
		// clone intermediate query.
		sql:    rtcq.sql.Clone(),
		path:   rtcq.path,
		unique: rtcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelatedTestCase.Query().
//		GroupBy(relatedtestcase.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rtcq *RelatedTestCaseQuery) GroupBy(field string, fields ...string) *RelatedTestCaseGroupBy {
	grbuild := &RelatedTestCaseGroupBy{config: rtcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rtcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rtcq.sqlQuery(ctx), nil
	}
	grbuild.label = relatedtestcase.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.RelatedTestCase.Query().
//		Select(relatedtestcase.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (rtcq *RelatedTestCaseQuery) Select(fields ...string) *RelatedTestCaseSelect {
	rtcq.fields = append(rtcq.fields, fields...)
	selbuild := &RelatedTestCaseSelect{RelatedTestCaseQuery: rtcq}
	selbuild.label = relatedtestcase.Label
	selbuild.flds, selbuild.scan = &rtcq.fields, selbuild.Scan
	return selbuild
}

func (rtcq *RelatedTestCaseQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rtcq.fields {
		if !relatedtestcase.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rtcq.path != nil {
		prev, err := rtcq.path(ctx)
		if err != nil {
			return err
		}
		rtcq.sql = prev
	}
	if relatedtestcase.Policy == nil {
		return errors.New("ent: uninitialized relatedtestcase.Policy (forgotten import ent/runtime?)")
	}
	if err := relatedtestcase.Policy.EvalQuery(ctx, rtcq); err != nil {
		return err
	}
	return nil
}

func (rtcq *RelatedTestCaseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelatedTestCase, error) {
	var (
		nodes = []*RelatedTestCase{}
		_spec = rtcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*RelatedTestCase).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &RelatedTestCase{config: rtcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rtcq.modifiers) > 0 {
		_spec.Modifiers = rtcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rtcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rtcq *RelatedTestCaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rtcq.querySpec()
	if len(rtcq.modifiers) > 0 {
		_spec.Modifiers = rtcq.modifiers
	}
	_spec.Node.Columns = rtcq.fields
	if len(rtcq.fields) > 0 {
		_spec.Unique = rtcq.unique != nil && *rtcq.unique
	}
	return sqlgraph.CountNodes(ctx, rtcq.driver, _spec)
}

func (rtcq *RelatedTestCaseQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rtcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rtcq *RelatedTestCaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   relatedtestcase.Table,
			Columns: relatedtestcase.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: relatedtestcase.FieldID,
			},
		},
		From:   rtcq.sql,
		Unique: true,
	}
	if unique := rtcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rtcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relatedtestcase.FieldID)
		for i := range fields {
			if fields[i] != relatedtestcase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rtcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rtcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rtcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rtcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rtcq *RelatedTestCaseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rtcq.driver.Dialect())
	t1 := builder.Table(relatedtestcase.Table)
	columns := rtcq.fields
	if len(columns) == 0 {
		columns = relatedtestcase.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rtcq.sql != nil {
		selector = rtcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rtcq.unique != nil && *rtcq.unique {
		selector.Distinct()
	}
	for _, m := range rtcq.modifiers {
		m(selector)
	}
	for _, p := range rtcq.predicates {
		p(selector)
	}
	for _, p := range rtcq.order {
		p(selector)
	}
	if offset := rtcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rtcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (rtcq *RelatedTestCaseQuery) ForUpdate(opts ...sql.LockOption) *RelatedTestCaseQuery {
	if rtcq.driver.Dialect() == dialect.Postgres {
		rtcq.Unique(false)
	}
	rtcq.modifiers = append(rtcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return rtcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (rtcq *RelatedTestCaseQuery) ForShare(opts ...sql.LockOption) *RelatedTestCaseQuery {
	if rtcq.driver.Dialect() == dialect.Postgres {
		rtcq.Unique(false)
	}
	rtcq.modifiers = append(rtcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return rtcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rtcq *RelatedTestCaseQuery) Modify(modifiers ...func(s *sql.Selector)) *RelatedTestCaseSelect {
	rtcq.modifiers = append(rtcq.modifiers, modifiers...)
	return rtcq.Select()
}

// RelatedTestCaseGroupBy is the group-by builder for RelatedTestCase entities.
type RelatedTestCaseGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rtcgb *RelatedTestCaseGroupBy) Aggregate(fns ...AggregateFunc) *RelatedTestCaseGroupBy {
	rtcgb.fns = append(rtcgb.fns, fns...)
	return rtcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rtcgb *RelatedTestCaseGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rtcgb.path(ctx)
	if err != nil {
		return err
	}
	rtcgb.sql = query
	return rtcgb.sqlScan(ctx, v)
}

func (rtcgb *RelatedTestCaseGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rtcgb.fields {
		if !relatedtestcase.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rtcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rtcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rtcgb *RelatedTestCaseGroupBy) sqlQuery() *sql.Selector {
	selector := rtcgb.sql.Select()
	aggregation := make([]string, 0, len(rtcgb.fns))
	for _, fn := range rtcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rtcgb.fields)+len(rtcgb.fns))
		for _, f := range rtcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rtcgb.fields...)...)
}

// RelatedTestCaseSelect is the builder for selecting fields of RelatedTestCase entities.
type RelatedTestCaseSelect struct {
	*RelatedTestCaseQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rtcs *RelatedTestCaseSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rtcs.prepareQuery(ctx); err != nil {
		return err
	}
	rtcs.sql = rtcs.RelatedTestCaseQuery.sqlQuery(ctx)
	return rtcs.sqlScan(ctx, v)
}

func (rtcs *RelatedTestCaseSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rtcs.sql.Query()
	if err := rtcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rtcs *RelatedTestCaseSelect) Modify(modifiers ...func(s *sql.Selector)) *RelatedTestCaseSelect {
	rtcs.modifiers = append(rtcs.modifiers, modifiers...)
	return rtcs
}
