// Code generated by ent, DO NOT EDIT.

package cond

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the cond type in the database.
	Label = "cond"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCondType holds the string denoting the cond_type field in the database.
	FieldCondType = "cond_type"
	// FieldTestCaseID holds the string denoting the test_case_id field in the database.
	FieldTestCaseID = "test_case_id"
	// FieldCondTestCaseID holds the string denoting the cond_test_case_id field in the database.
	FieldCondTestCaseID = "cond_test_case_id"
	// FieldArgumentMap holds the string denoting the argument_map field in the database.
	FieldArgumentMap = "argument_map"
	// FieldIndex holds the string denoting the index field in the database.
	FieldIndex = "index"
	// Table holds the table name of the cond in the database.
	Table = "conds"
)

// Columns holds all SQL columns for cond fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCondType,
	FieldTestCaseID,
	FieldCondTestCaseID,
	FieldArgumentMap,
	FieldIndex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/smoketest-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultCondType holds the default value on creation for the "cond_type" field.
	DefaultCondType string
	// DefaultTestCaseID holds the default value on creation for the "test_case_id" field.
	DefaultTestCaseID func() uuid.UUID
	// DefaultCondTestCaseID holds the default value on creation for the "cond_test_case_id" field.
	DefaultCondTestCaseID func() uuid.UUID
	// DefaultArgumentMap holds the default value on creation for the "argument_map" field.
	DefaultArgumentMap string
	// DefaultIndex holds the default value on creation for the "index" field.
	DefaultIndex uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
