// Code generated by ent, DO NOT EDIT.

package cond

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/smoketest-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// EntID applies equality check predicate on the "ent_id" field. It's identical to EntIDEQ.
func EntID(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// CondType applies equality check predicate on the "cond_type" field. It's identical to CondTypeEQ.
func CondType(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCondType), v))
	})
}

// TestCaseID applies equality check predicate on the "test_case_id" field. It's identical to TestCaseIDEQ.
func TestCaseID(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTestCaseID), v))
	})
}

// CondTestCaseID applies equality check predicate on the "cond_test_case_id" field. It's identical to CondTestCaseIDEQ.
func CondTestCaseID(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCondTestCaseID), v))
	})
}

// ArgumentMap applies equality check predicate on the "argument_map" field. It's identical to ArgumentMapEQ.
func ArgumentMap(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArgumentMap), v))
	})
}

// Index applies equality check predicate on the "index" field. It's identical to IndexEQ.
func Index(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIndex), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// EntIDEQ applies the EQ predicate on the "ent_id" field.
func EntIDEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// EntIDNEQ applies the NEQ predicate on the "ent_id" field.
func EntIDNEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEntID), v))
	})
}

// EntIDIn applies the In predicate on the "ent_id" field.
func EntIDIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldEntID), v...))
	})
}

// EntIDNotIn applies the NotIn predicate on the "ent_id" field.
func EntIDNotIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldEntID), v...))
	})
}

// EntIDGT applies the GT predicate on the "ent_id" field.
func EntIDGT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEntID), v))
	})
}

// EntIDGTE applies the GTE predicate on the "ent_id" field.
func EntIDGTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEntID), v))
	})
}

// EntIDLT applies the LT predicate on the "ent_id" field.
func EntIDLT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEntID), v))
	})
}

// EntIDLTE applies the LTE predicate on the "ent_id" field.
func EntIDLTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEntID), v))
	})
}

// CondTypeEQ applies the EQ predicate on the "cond_type" field.
func CondTypeEQ(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCondType), v))
	})
}

// CondTypeNEQ applies the NEQ predicate on the "cond_type" field.
func CondTypeNEQ(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCondType), v))
	})
}

// CondTypeIn applies the In predicate on the "cond_type" field.
func CondTypeIn(vs ...string) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCondType), v...))
	})
}

// CondTypeNotIn applies the NotIn predicate on the "cond_type" field.
func CondTypeNotIn(vs ...string) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCondType), v...))
	})
}

// CondTypeGT applies the GT predicate on the "cond_type" field.
func CondTypeGT(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCondType), v))
	})
}

// CondTypeGTE applies the GTE predicate on the "cond_type" field.
func CondTypeGTE(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCondType), v))
	})
}

// CondTypeLT applies the LT predicate on the "cond_type" field.
func CondTypeLT(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCondType), v))
	})
}

// CondTypeLTE applies the LTE predicate on the "cond_type" field.
func CondTypeLTE(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCondType), v))
	})
}

// CondTypeContains applies the Contains predicate on the "cond_type" field.
func CondTypeContains(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCondType), v))
	})
}

// CondTypeHasPrefix applies the HasPrefix predicate on the "cond_type" field.
func CondTypeHasPrefix(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCondType), v))
	})
}

// CondTypeHasSuffix applies the HasSuffix predicate on the "cond_type" field.
func CondTypeHasSuffix(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCondType), v))
	})
}

// CondTypeIsNil applies the IsNil predicate on the "cond_type" field.
func CondTypeIsNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCondType)))
	})
}

// CondTypeNotNil applies the NotNil predicate on the "cond_type" field.
func CondTypeNotNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCondType)))
	})
}

// CondTypeEqualFold applies the EqualFold predicate on the "cond_type" field.
func CondTypeEqualFold(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCondType), v))
	})
}

// CondTypeContainsFold applies the ContainsFold predicate on the "cond_type" field.
func CondTypeContainsFold(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCondType), v))
	})
}

// TestCaseIDEQ applies the EQ predicate on the "test_case_id" field.
func TestCaseIDEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDNEQ applies the NEQ predicate on the "test_case_id" field.
func TestCaseIDNEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDIn applies the In predicate on the "test_case_id" field.
func TestCaseIDIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTestCaseID), v...))
	})
}

// TestCaseIDNotIn applies the NotIn predicate on the "test_case_id" field.
func TestCaseIDNotIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTestCaseID), v...))
	})
}

// TestCaseIDGT applies the GT predicate on the "test_case_id" field.
func TestCaseIDGT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDGTE applies the GTE predicate on the "test_case_id" field.
func TestCaseIDGTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDLT applies the LT predicate on the "test_case_id" field.
func TestCaseIDLT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDLTE applies the LTE predicate on the "test_case_id" field.
func TestCaseIDLTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTestCaseID), v))
	})
}

// TestCaseIDIsNil applies the IsNil predicate on the "test_case_id" field.
func TestCaseIDIsNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldTestCaseID)))
	})
}

// TestCaseIDNotNil applies the NotNil predicate on the "test_case_id" field.
func TestCaseIDNotNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldTestCaseID)))
	})
}

// CondTestCaseIDEQ applies the EQ predicate on the "cond_test_case_id" field.
func CondTestCaseIDEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDNEQ applies the NEQ predicate on the "cond_test_case_id" field.
func CondTestCaseIDNEQ(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDIn applies the In predicate on the "cond_test_case_id" field.
func CondTestCaseIDIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCondTestCaseID), v...))
	})
}

// CondTestCaseIDNotIn applies the NotIn predicate on the "cond_test_case_id" field.
func CondTestCaseIDNotIn(vs ...uuid.UUID) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCondTestCaseID), v...))
	})
}

// CondTestCaseIDGT applies the GT predicate on the "cond_test_case_id" field.
func CondTestCaseIDGT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDGTE applies the GTE predicate on the "cond_test_case_id" field.
func CondTestCaseIDGTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDLT applies the LT predicate on the "cond_test_case_id" field.
func CondTestCaseIDLT(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDLTE applies the LTE predicate on the "cond_test_case_id" field.
func CondTestCaseIDLTE(v uuid.UUID) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCondTestCaseID), v))
	})
}

// CondTestCaseIDIsNil applies the IsNil predicate on the "cond_test_case_id" field.
func CondTestCaseIDIsNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldCondTestCaseID)))
	})
}

// CondTestCaseIDNotNil applies the NotNil predicate on the "cond_test_case_id" field.
func CondTestCaseIDNotNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldCondTestCaseID)))
	})
}

// ArgumentMapEQ applies the EQ predicate on the "argument_map" field.
func ArgumentMapEQ(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapNEQ applies the NEQ predicate on the "argument_map" field.
func ArgumentMapNEQ(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapIn applies the In predicate on the "argument_map" field.
func ArgumentMapIn(vs ...string) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldArgumentMap), v...))
	})
}

// ArgumentMapNotIn applies the NotIn predicate on the "argument_map" field.
func ArgumentMapNotIn(vs ...string) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldArgumentMap), v...))
	})
}

// ArgumentMapGT applies the GT predicate on the "argument_map" field.
func ArgumentMapGT(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapGTE applies the GTE predicate on the "argument_map" field.
func ArgumentMapGTE(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapLT applies the LT predicate on the "argument_map" field.
func ArgumentMapLT(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapLTE applies the LTE predicate on the "argument_map" field.
func ArgumentMapLTE(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapContains applies the Contains predicate on the "argument_map" field.
func ArgumentMapContains(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapHasPrefix applies the HasPrefix predicate on the "argument_map" field.
func ArgumentMapHasPrefix(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapHasSuffix applies the HasSuffix predicate on the "argument_map" field.
func ArgumentMapHasSuffix(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapIsNil applies the IsNil predicate on the "argument_map" field.
func ArgumentMapIsNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldArgumentMap)))
	})
}

// ArgumentMapNotNil applies the NotNil predicate on the "argument_map" field.
func ArgumentMapNotNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldArgumentMap)))
	})
}

// ArgumentMapEqualFold applies the EqualFold predicate on the "argument_map" field.
func ArgumentMapEqualFold(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldArgumentMap), v))
	})
}

// ArgumentMapContainsFold applies the ContainsFold predicate on the "argument_map" field.
func ArgumentMapContainsFold(v string) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldArgumentMap), v))
	})
}

// IndexEQ applies the EQ predicate on the "index" field.
func IndexEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIndex), v))
	})
}

// IndexNEQ applies the NEQ predicate on the "index" field.
func IndexNEQ(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIndex), v))
	})
}

// IndexIn applies the In predicate on the "index" field.
func IndexIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldIndex), v...))
	})
}

// IndexNotIn applies the NotIn predicate on the "index" field.
func IndexNotIn(vs ...uint32) predicate.Cond {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldIndex), v...))
	})
}

// IndexGT applies the GT predicate on the "index" field.
func IndexGT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIndex), v))
	})
}

// IndexGTE applies the GTE predicate on the "index" field.
func IndexGTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIndex), v))
	})
}

// IndexLT applies the LT predicate on the "index" field.
func IndexLT(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIndex), v))
	})
}

// IndexLTE applies the LTE predicate on the "index" field.
func IndexLTE(v uint32) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIndex), v))
	})
}

// IndexIsNil applies the IsNil predicate on the "index" field.
func IndexIsNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldIndex)))
	})
}

// IndexNotNil applies the NotNil predicate on the "index" field.
func IndexNotNil() predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldIndex)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cond) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cond) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cond) predicate.Cond {
	return predicate.Cond(func(s *sql.Selector) {
		p(s.Not())
	})
}
