// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Detail is the predicate function for detail builders.
type Detail func(*sql.Selector)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// RelatedTestCase is the predicate function for relatedtestcase builders.
type RelatedTestCase func(*sql.Selector)

// TestCase is the predicate function for testcase builders.
type TestCase func(*sql.Selector)
